source 'https://github.com/KATracking/AppicAdSpecs'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'


platform :ios, '10.3'

target 'daojishi' do
  pod 'BmobSDK', '~>2.3.1'
  pod 'SVProgressHUD', '~>2.2.5'
  pod 'pop', '~>1.0.12'
  pod 'Masonry', '~>1.1.0'
  pod 'BaiduMobStatCodeless' , '~> 4.9.5'
  pod 'NorthCityTool'


end
